@extends('layouts.admin')
@section('title', 'Alumni Track | Admin')
@section('page-title', 'Alumni Track')
@section('content')
<div class="alumni-page">
<div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4"><div><div class="admin-breadcrumb">ADMIN <span>/</span> ALUMNI</div><h1 class="alumni-title">Alumni Track</h1><p class="alumni-subtitle">Kelola dan pantau perkembangan alumni setelah lulus.</p></div><a href="{{ route('admin.module.create', 'alumni') }}" class="btn btn-primary"><i class="bi bi-plus-lg me-1"></i>Tambah Alumni</a></div>
<div class="row g-3 mb-4">@foreach([['total','Total Alumni','bi-people-fill','blue'],['bekerja','Bekerja','bi-briefcase-fill','green'],['wirausaha','Wirausaha','bi-shop','orange'],['mencari_kerja','Mencari Kerja','bi-search','purple']] as [$key,$label,$icon,$color])<div class="col-12 col-sm-6 col-xl-3"><div class="alumni-stat"><div class="stat-icon {{ $color }}"><i class="bi {{ $icon }}"></i></div><div><div class="stat-label">{{ $label }}</div><div class="stat-value">{{ $stats[$key] }}</div></div></div></div>@endforeach</div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="dashboard-card alumni-table-card"><div class="dashboard-card-header flex-wrap gap-3"><div><h2 class="dashboard-card-title">Data Alumni</h2><p class="dashboard-card-subtitle">Daftar alumni dan status terbaru.</p></div><form class="alumni-filters" method="get"><div class="input-group"><span class="input-group-text"><i class="bi bi-search"></i></span><input class="form-control" name="search" value="{{ $search }}" placeholder="Cari nama, NISN, jurusan..."></div><select class="form-select" name="status"><option value="">Semua status</option>@foreach(['bekerja'=>'Bekerja','kuliah'=>'Kuliah','wirausaha'=>'Wirausaha','mencari_kerja'=>'Mencari kerja'] as $value=>$label)<option value="{{ $value }}" @selected($status === $value)>{{ $label }}</option>@endforeach</select><button class="btn btn-outline-primary">Filter</button></form></div>
<div class="table-responsive"><table class="table dashboard-table alumni-table align-middle mb-0"><thead><tr><th>Alumni</th><th>Jurusan</th><th>Tahun Lulus</th><th>Status</th><th>Perusahaan / Usaha</th><th class="text-end">Aksi</th></tr></thead><tbody>@forelse($items as $item)<tr><td><div class="student-info"><div class="student-avatar primary">{{ strtoupper(substr($item->siswa?->nama_siswa ?? 'A', 0, 1)) }}</div><div><strong>{{ $item->siswa?->nama_siswa ?? 'Alumni #'.$item->id_alumni }}</strong><small>{{ $item->siswa?->nisn ?? 'NISN tidak tersedia' }}</small></div></div></td><td><span class="major-badge">{{ $item->jurusan?->nama_jurusan ?? $item->siswa?->jurusan?->nama_jurusan ?? '-' }}</span></td><td>{{ $item->tahun_lulus ?? '-' }}</td><td><span class="status-pill status-{{ $item->status }}">{{ $item->statusLabel() }}</span></td><td class="description-cell">{{ $item->keterangan ?: '-' }}</td><td class="text-end text-nowrap"><a class="action-btn edit" href="{{ route('admin.module.edit', ['alumni',$item->id_alumni]) }}" title="Edit"><i class="bi bi-pencil"></i></a><form class="d-inline" method="post" action="{{ route('admin.module.destroy', ['alumni',$item->id_alumni]) }}" onsubmit="return confirm('Hapus data alumni ini?')">@csrf @method('delete')<button class="action-btn delete" title="Hapus"><i class="bi bi-trash"></i></button></form></td></tr>@empty<tr><td colspan="6" class="empty-state"><i class="bi bi-inbox"></i><strong>Belum ada data alumni</strong><span>Data alumni yang ditambahkan akan tampil di sini.</span></td></tr>@endforelse</tbody></table></div>@if($items->hasPages())<div class="p-3">{{ $items->links() }}</div>@endif</div></div>
@endsection