@extends('layouts.admin')
@section('title', ($item ? 'Edit ' : 'Tambah ') . ucwords(str_replace('-', ' ', $type)))
@section('page-title', ($item ? 'Edit ' : 'Tambah ') . ucwords(str_replace('-', ' ', $type)))
@section('content')
<div class="dashboard-card"><div class="dashboard-card-header"><div><h2 class="dashboard-card-title">{{ $item ? 'Edit' : 'Tambah' }} {{ ucwords(str_replace('-', ' ', $type)) }}</h2><p class="dashboard-card-subtitle">Lengkapi informasi lalu simpan perubahan.</p></div></div><div class="p-4">@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif<form method="post" action="{{ $item ? route('admin.module.update', [$type, $item->getKey()]) : route('admin.module.store', $type) }}">@csrf @if($item) @method('put') @endif
@if($type === 'berita') @include('admin.partials.field', ['name'=>'judul','label'=>'Judul','value'=>$item->judul??'']) @include('admin.partials.field', ['name'=>'slug','label'=>'Slug','value'=>$item->slug??''])<div class="mb-3"><label class="form-label">Isi</label><textarea name="isi" class="form-control" rows="6" required>{{ old('isi', $item->isi??'') }}</textarea></div><div class="mb-3"><label class="form-label">Status</label><select name="status" class="form-select"><option>Draft</option><option>Terbit</option></select></div>
@elseif($type === 'prestasi') @foreach(['judul_prestasi'=>'Judul','nama_pemenang'=>'Pemenang','kelas'=>'Kelas','tingkat'=>'Tingkat','juara'=>'Juara','tahun'=>'Tahun'] as $name=>$label) @include('admin.partials.field', compact('name','label')) @endforeach<div class="mb-3"><label class="form-label">Deskripsi</label><textarea name="deskripsi" class="form-control" rows="4">{{ old('deskripsi', $item->deskripsi??'') }}</textarea></div>
@elseif($type === 'unduh-informasi') @foreach(['judul'=>'Judul','slug'=>'Slug','nama_file'=>'Nama file','file_path'=>'Path file'] as $name=>$label) @include('admin.partials.field', compact('name','label')) @endforeach
@else <div class="row g-3"><div class="col-md-6"><label class="form-label">Siswa</label><select name="id_siswa" class="form-select"><option value="">Pilih siswa (opsional)</option>@foreach($siswa as $row)<option value="{{ $row->id_siswa }}" @selected(old('id_siswa', $item->id_siswa??'') == $row->id_siswa)>{{ $row->nama_siswa }} - {{ $row->nisn }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Jurusan</label><select name="id_jurusan" class="form-select"><option value="">Pilih jurusan</option>@foreach($jurusan as $row)<option value="{{ $row->id_jurusan }}" @selected(old('id_jurusan', $item->id_jurusan??'') == $row->id_jurusan)>{{ $row->nama_jurusan }}</option>@endforeach</select></div></div>@foreach(['tahun_lulus'=>'Tahun lulus','no_telp'=>'Telepon','email'=>'Email'] as $name=>$label) @include('admin.partials.field', compact('name','label')) @endforeach<div class="mb-3"><label class="form-label">Status</label><select name="status" class="form-select">@foreach(['bekerja'=>'Bekerja','kuliah'=>'Kuliah','wirausaha'=>'Wirausaha','mencari_kerja'=>'Mencari kerja'] as $value=>$label)<option value="{{ $value }}" @selected(old('status', $item->status??'mencari_kerja') === $value)>{{ $label }}</option>@endforeach</select></div><div class="mb-3"><label class="form-label">Keterangan</label><textarea name="keterangan" class="form-control">{{ old('keterangan', $item->keterangan??'') }}</textarea></div><div class="form-check mb-3"><input type="checkbox" name="mentor" value="1" class="form-check-input" @checked(old('mentor', $item->mentor??false))><label class="form-check-label">Mentor</label></div>@endif
<button class="btn btn-primary">Simpan</button> <a href="{{ route('admin.module', $type) }}" class="btn btn-light">Batal</a></form></div></div>
@endsection