@extends('layouts.admin')
@section('title', ($item ? 'Edit' : 'Tambah').' Mentoring | Admin')
@section('page-title', ($item ? 'Edit' : 'Tambah').' Mentoring')
@section('content')
<div class="dashboard-card mentoring-form-card"><div class="dashboard-card-header"><div><h1 class="dashboard-card-title">{{ $item ? 'Edit Data Mentoring' : 'Tambah Data Mentoring' }}</h1><p class="dashboard-card-subtitle">Lengkapi data peserta, mentor, dan topik pendampingan.</p></div></div>
<form method="post" action="{{ $item ? route('admin.mentoring.update',$item->id) : route('admin.mentoring.store') }}" class="p-4">@csrf @if($item) @method('PUT') @endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="row g-3"><div class="col-md-6"><label class="form-label">Nama siswa <span class="text-danger">*</span></label><input name="nama_siswa" class="form-control" value="{{ old('nama_siswa',$item->nama_siswa??'') }}" required></div>
<div class="col-md-6"><label class="form-label">Nomor telepon</label><input type="tel" name="no_telp" class="form-control" value="{{ old('no_telp',$item->no_telp??'') }}" inputmode="numeric" pattern="[0-9]{10,15}" minlength="10" maxlength="15"></div>
 <div class="col-md-6"><label class="form-label">Siswa terdaftar</label><select name="id_siswa" class="form-select"><option value="">Pilih siswa (opsional)</option>@foreach($siswa as $row)<option value="{{ $row->id_siswa }}" @selected(old('id_siswa',$item->id_siswa??'')==$row->id_siswa)>{{ $row->nama_siswa }}{{ $row->kelas ? ' - '.$row->kelas : '' }}</option>@endforeach</select></div>
<div class="col-md-4"><label class="form-label">Jurusan</label><select name="id_jurusan" class="form-select"><option value="">Pilih jurusan</option>@foreach($jurusan as $row)<option value="{{ $row->id_jurusan }}" @selected(old('id_jurusan',$item->id_jurusan??'')==$row->id_jurusan)>{{ $row->nama_jurusan }}</option>@endforeach</select></div>
<div class="col-md-4"><label class="form-label">Kelas</label><input name="kelas" class="form-control" value="{{ old('kelas',$item->kelas??'') }}"></div>
<div class="col-md-4"><label class="form-label">Tanggal</label><input type="date" name="tanggal" class="form-control" value="{{ old('tanggal',isset($item->tanggal)?$item->tanggal?->format('Y-m-d'):'') }}"></div>
<div class="col-md-6"><label class="form-label">Mentor alumni</label><select name="id_alumni" class="form-select"><option value="">Pilih mentor (opsional)</option>@foreach($mentors as $mentor)<option value="{{ $mentor->id_alumni }}" @selected(old('id_alumni',$item->id_alumni??'')==$mentor->id_alumni)>{{ $mentor->siswa?->nama_siswa ?? 'Alumni #'.$mentor->id_alumni }}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label">Nama mentor manual</label><input name="nama_mentor" class="form-control" value="{{ old('nama_mentor',$item->nama_mentor??'') }}" placeholder="Jika mentor belum terhubung"></div>
<div class="col-md-8"><label class="form-label">Topik mentoring <span class="text-danger">*</span></label><input name="topik_mentoring" class="form-control" value="{{ old('topik_mentoring',$item->topik_mentoring??'') }}" required></div>
<div class="col-md-4"><label class="form-label">Status <span class="text-danger">*</span></label><select name="status" class="form-select" required>@foreach(['pending'=>'Pending','diproses'=>'Diproses','selesai'=>'Selesai'] as $value=>$label)<option value="{{ $value }}" @selected(old('status',$item->status??'pending')===$value)>{{ $label }}</option>@endforeach</select></div>
<div class="col-12"><label class="form-label">Catatan</label><textarea name="catatan" class="form-control" rows="4">{{ old('catatan',$item->catatan??'') }}</textarea></div></div><div class="d-flex gap-2 mt-4"><button class="btn btn-primary"><i class="bi bi-save me-1"></i>Simpan</button><a href="{{ route('admin.mentoring') }}" class="btn btn-light">Batal</a></div></form></div>
@endsection