server {
    listen 80;
    server_name localhost;

    root /var/www/public;
    index index.php index.html;

    # Laravel
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP-FPM
    location ~ \.php$ {
        try_files $uri =404;

        fastcgi_pass app:9000;
        fastcgi_index index.php;

        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;

        # Performance
        fastcgi_buffering on;
        fastcgi_buffer_size 16k;
        fastcgi_buffers 4 16k;

        fastcgi_connect_timeout 60s;
        fastcgi_send_timeout 60s;
        fastcgi_read_timeout 60s;
    }

    # Cache static assets
    location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg|webp|avif|woff|woff2|ttf)$ {
        expires 7d;
        add_header Cache-Control "public, max-age=604800, immutable";

        try_files $uri =404;
    }

    # Jangan izinkan akses file .ht*
    location ~ /\.ht {
        deny all;
    }

    # Jangan izinkan akses file environment
    location ~ /\.(?!well-known).* {
        deny all;
    }
}