<?php
namespace App\Http\Controllers;
use App\Http\Requests\MentoringRequest;
use App\Models\{AlumniTrack, Prestasi, Berita, UnduhInformasi, BookingTefa, Siswa, Jurusan, Mentoring};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Schema;
class AdminController extends Controller
{
 public function login(){return view('admin.login');}
 public function authenticate(Request $request){$credentials=$request->validate(['username'=>'required|string','password'=>'required']);if(Auth::attempt(['username'=>$credentials['username'],'password'=>$credentials['password'],'is_admin'=>true])){$request->session()->regenerate();return redirect()->route('dashboard');}Auth::logout();return back()->withErrors(['username'=>'Username atau kata sandi tidak valid.']);}
 public function logout(Request $request){Auth::logout();$request->session()->invalidate();$request->session()->regenerateToken();return redirect()->route('login');}
 private function models():array{return ['prestasi'=>Prestasi::class,'berita'=>Berita::class,'unduh-informasi'=>UnduhInformasi::class,'alumni'=>AlumniTrack::class,'tefa'=>BookingTefa::class];}
 public function dashboard(){return view('dashboard',['counts'=>['alumni'=>AlumniTrack::count(),'prestasi'=>Prestasi::count(),'berita'=>Berita::count(),'informasi'=>UnduhInformasi::count(),'tefa'=>BookingTefa::count()]]);}
 public function mentoring(Request $request){
  $search=trim((string)$request->query('search','')); $status=(string)$request->query('status','');
  $query=Mentoring::with(['siswa','jurusan','alumni']);
  if($search!=='')$query->where(function($q)use($search){$q->where('nama_siswa','like','%'.$search.'%')->orWhere('nama_mentor','like','%'.$search.'%')->orWhere('topik_mentoring','like','%'.$search.'%');});
  if($status!=='')$query->where('status',$status);
  $items=$query->latest()->paginate(20)->withQueryString();
  $stats=['total'=>Mentoring::count(),'menunggu'=>Mentoring::where('status','pending')->count(),'proses'=>Mentoring::where('status','diproses')->count(),'selesai'=>Mentoring::where('status','selesai')->count()];
  return view('admin.mentoring',compact('items','stats','search','status'));
 }
 public function createMentoring(){return view('admin.mentoring-form',['item'=>null,'siswa'=>Siswa::with('jurusan')->orderBy('nama_siswa')->get(),'jurusan'=>Jurusan::orderBy('nama_jurusan')->get(),'mentors'=>AlumniTrack::with('siswa')->where('mentor',true)->whereNotNull('id_siswa')->get()]);}
 public function storeMentoring(MentoringRequest $request){Mentoring::create($request->validated());return redirect()->route('admin.mentoring')->with('success','Data mentoring berhasil ditambahkan.');}
 public function editMentoring(int $id){return view('admin.mentoring-form',['item'=>Mentoring::findOrFail($id),'siswa'=>Siswa::with('jurusan')->orderBy('nama_siswa')->get(),'jurusan'=>Jurusan::orderBy('nama_jurusan')->get(),'mentors'=>AlumniTrack::with('siswa')->where('mentor',true)->whereNotNull('id_siswa')->get()]);}
 public function updateMentoring(MentoringRequest $request,int $id){Mentoring::findOrFail($id)->update($request->validated());return redirect()->route('admin.mentoring')->with('success','Data mentoring berhasil diperbarui.');}
 public function destroyMentoring(int $id){Mentoring::findOrFail($id)->delete();return back()->with('success','Data mentoring berhasil dihapus.');}
  public function index(Request $request,string $type){$map=$this->models();abort_unless(isset($map[$type]),404);if($type==='alumni'){$search=trim((string)$request->query('search',''));$status=(string)$request->query('status','');$query=AlumniTrack::with(['siswa.jurusan','jurusan']);if($search!=='')$query->where(function($q)use($search){$q->where('tahun_lulus','like','%'.$search.'%')->orWhere('status','like','%'.$search.'%')->orWhere('keterangan','like','%'.$search.'%')->orWhereHas('siswa',function($s)use($search){$s->where('nama_siswa','like','%'.$search.'%')->orWhere('nisn','like','%'.$search.'%');})->orWhereHas('jurusan',fn($j)=>$j->where('nama_jurusan','like','%'.$search.'%'));});if(in_array($status,['bekerja','kuliah','wirausaha','mencari_kerja'],true))$query->where('status',$status);$stats=['total'=>AlumniTrack::count(),'bekerja'=>AlumniTrack::where('status','bekerja')->count(),'wirausaha'=>AlumniTrack::where('status','wirausaha')->count(),'mencari_kerja'=>AlumniTrack::where('status','mencari_kerja')->count()];$items=$query->latest()->paginate(15)->withQueryString();return view('admin.alumni',compact('items','stats','search','status'));}$query=$map[$type]::query();if($type==='tefa')$query->with('transaksi.layanan');return view('admin.index',['type'=>$type,'items'=>$query->latest()->paginate(20)]);}
 public function create(string $type){abort_unless(array_key_exists($type,$this->models())&&$type!=='tefa',404);return view('admin.form',['type'=>$type,'item'=>null,'siswa'=>Siswa::with('jurusan')->orderBy('nama_siswa')->get(),'jurusan'=>Jurusan::orderBy('nama_jurusan')->get()]);}
 public function store(Request $request,string $type){$this->models()[$type]::create($this->validated($request,$type));return redirect()->route('admin.module',$type)->with('success','Data berhasil ditambahkan.');}
 public function edit(string $type,int $id){abort_unless(array_key_exists($type,$this->models())&&$type!=='tefa',404);return view('admin.form',['type'=>$type,'item'=>$this->models()[$type]::findOrFail($id),'siswa'=>Siswa::with('jurusan')->orderBy('nama_siswa')->get(),'jurusan'=>Jurusan::orderBy('nama_jurusan')->get()]);}
 public function update(Request $request,string $type,int $id){$item=$this->models()[$type]::findOrFail($id);$item->update($this->validated($request,$type,$item));return redirect()->route('admin.module',$type)->with('success','Data berhasil diperbarui.');}
 private function validated(Request $request,string $type,$item=null):array{$key=$item?->getKey()??'NULL';$rules=['berita'=>['judul'=>'required|string|max:255','slug'=>'required|string|max:255|unique:berita,slug,'.$key.',id_berita','isi'=>'required|string','status'=>'required|in:Draft,Terbit'],'prestasi'=>['judul_prestasi'=>'required|string|max:255','nama_pemenang'=>'required|string|max:255','kelas'=>'nullable|string|max:255','tingkat'=>'nullable|string|max:255','juara'=>'nullable|string|max:255','tahun'=>'nullable|integer|min:1900|max:2200','deskripsi'=>'nullable|string'],'unduh-informasi'=>['judul'=>'required|string|max:255','slug'=>'required|string|max:255|unique:unduh_informasi,slug,'.$key.',id_informasi','nama_file'=>'required|string|max:255','file_path'=>'required|string|max:255'],'alumni'=>['id_siswa'=>'nullable|exists:siswa,id_siswa','id_jurusan'=>'nullable|exists:jurusan,id_jurusan','tahun_lulus'=>'required|integer|min:1900|max:2200','no_telp'=>'nullable|string|max:20','email'=>'nullable|email|max:150','status'=>'required|in:bekerja,kuliah,wirausaha,mencari_kerja','keterangan'=>'nullable|string','mentor'=>'nullable|boolean']];abort_unless(isset($rules[$type]),404);$data=$request->validate($rules[$type]);if($type==='alumni')$data['mentor']=$request->boolean('mentor');return $data;}
 public function destroy(string $type,int $id){$map=$this->models();abort_unless(isset($map[$type])&&$type!=='tefa',404);$map[$type]::findOrFail($id)->delete();return back()->with('success','Data berhasil dihapus.');}
 public function updateTefaStatus(Request $request,int $id){$booking=BookingTefa::findOrFail($id);$booking->update($request->validate(['status_book'=>'required|in:pending,diproses,selesai,batal']));return back()->with('success','Status booking TEFA diperbarui.');}
}
